/vis/disable
#/control/execute ./visu.mac

/gate/geometry/setMaterialDatabase ./GateMaterials.db
/control/execute ./physics.mac

#/control/execute ./geometry.mac           # one ring new clearpem
/control/execute ./geometry-complete.mac  # n plates clearpem

#/control/execute ./phantomSphere.mac
/control/execute ./phantomCylinder.mac
/control/execute ./attachToSystem.mac

# INITIALIZE
/gate/run/initialize


/control/execute ./sourceCylinder.mac
/control/execute ./sourceSphere.mac

/gate/source/sourceNa22/setActivity 90000 becquerel

/gate/source/Na22_Z0_X0/setActivity 0.0113 becquerel
/gate/source/Na22_Z0_X1/setActivity 0.0113 becquerel
/gate/source/Na22_Z0_X2/setActivity 0.0113 becquerel
/gate/source/Na22_Z0_X3/setActivity 0.0113 becquerel
/gate/source/Na22_Z0_X4/setActivity 0.0113 becquerel
/gate/source/Na22_Z0_X5/setActivity 0.0113 becquerel
/gate/source/Na22_Z0_X6/setActivity 0.0113 becquerel
/gate/source/Na22_Z0_X7/setActivity 0.0113 becquerel

/gate/source/Na22_Z1_X0/setActivity 0.0113 becquerel
/gate/source/Na22_Z1_X1/setActivity 0.0113 becquerel
/gate/source/Na22_Z1_X2/setActivity 0.0113 becquerel
/gate/source/Na22_Z1_X3/setActivity 0.0113 becquerel
/gate/source/Na22_Z1_X4/setActivity 0.0113 becquerel
/gate/source/Na22_Z1_X5/setActivity 0.0113 becquerel
/gate/source/Na22_Z1_X6/setActivity 0.0113 becquerel
/gate/source/Na22_Z1_X7/setActivity 0.0113 becquerel


/gate/source/Na22_Z0_X8/setActivity  3.35 becquerel
/gate/source/Na22_Z0_X9/setActivity  3.35 becquerel
/gate/source/Na22_Z0_X10/setActivity 3.35 becquerel
/gate/source/Na22_Z0_X11/setActivity 3.35 becquerel
/gate/source/Na22_Z0_X12/setActivity 3.35 becquerel
/gate/source/Na22_Z0_X13/setActivity 3.35 becquerel
/gate/source/Na22_Z0_X14/setActivity 3.35 becquerel

/gate/source/Na22_Z1_X8/setActivity  3.35 becquerel
/gate/source/Na22_Z1_X9/setActivity  3.35 becquerel
/gate/source/Na22_Z1_X10/setActivity 3.35 becquerel
/gate/source/Na22_Z1_X11/setActivity 3.35 becquerel
/gate/source/Na22_Z1_X12/setActivity 3.35 becquerel
/gate/source/Na22_Z1_X13/setActivity 3.35 becquerel
/gate/source/Na22_Z1_X14/setActivity 3.35 becquerel


/gate/geometry/rebuild

#/control/execute ./digitizer.mac

# ROOT Output format
/gate/output/root/enable
/gate/output/root/setFileName TenSec
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setRootCoincidencesFlag 0

/gate/application/setTimeSlice     10  s
/gate/application/setTimeStart     0.   s
/gate/application/setTimeStop      10  s
# S T A R T  the A C Q U I S I T I O N
/gate/application/startDAQ
